import Link from "next/link";
import { CommunityLatestReports, CommunityMapPreview, CommunityStats } from "@/components/landing/community-live-sections";

function WorldMap() {
  return <div className="world-map" aria-hidden="true" />;
}

function NetworkDecor() {
  return <><span className="map-dot dot-one" /><span className="map-dot dot-two" /><span className="map-dot dot-three" /><span className="map-dot dot-four" /><svg className="network-line" viewBox="0 0 700 360" aria-hidden="true"><path d="M20 92c120-90 155 58 275-4s175-74 385 80" /><path d="M120 318c105-108 180-37 252-130s163-65 284-136" /></svg></>;
}

export default function Home() {
  return <div className="site-shell">
    <div className="map-background"><WorldMap /><WorldMap /><WorldMap /><WorldMap /><NetworkDecor /></div>
    <header className="site-header"><div className="site-header-inner"><Link href="/" className="brand" aria-label="JALANIN beranda"><span className="brand-logo" aria-hidden="true" /><span>JALANIN</span></Link><nav><Link className="active" href="/map">Peta kondisi</Link><a href="#cara-kerja">Cara kerja</a><a href="#tentang">Tentang</a></nav><div className="header-actions"><Link href="/login" className="login-link"><span className="google-mini-mark" aria-hidden="true">G</span>Masuk</Link><Link href="/reports/new" className="button button-accent">Laporkan jalan <span>-&gt;</span></Link></div><details className="mobile-menu"><summary aria-label="Buka menu">Menu</summary><div><Link href="/map">Peta kondisi</Link><a href="#cara-kerja">Cara kerja</a><a href="#tentang">Tentang</a><Link href="/login">Masuk</Link><Link href="/reports/new" className="button button-accent">Laporkan jalan <span>-&gt;</span></Link></div></details></div></header>

    <main>
      <section className="hero section-wrap"><div className="hero-copy reveal"><p className="eyebrow"><span /> Jalan Aman, Kota Nyaman</p><h1>Jalan yang lebih baik<br />dimulai dari <em>kepedulian kita.</em></h1><p className="hero-intro">Laporkan kerusakan jalan di sekitar Anda, lihat kondisi jalan, dan ikut mengawal perbaikannya secara terbuka.</p><div className="hero-actions"><Link href="/reports/new" className="button button-accent">Buat laporan <span>-&gt;</span></Link><Link href="/map" className="text-link">Jelajahi peta <span>-&gt;</span></Link></div><div className="hero-proof"><span className="proof-dots"><i /><i /><i /></span><span>Dipantau bersama oleh warga</span></div></div><div className="hero-visual reveal reveal-delay"><div className="road-photo photo-main" /><div className="road-photo photo-side" /><span className="visual-route" /><span className="visual-pin pin-red" /><span className="visual-pin pin-yellow" /><div className="hero-report-card"><span className="report-card-kicker"><span className="status-dot high" /> Laporan terbaru</span><strong>Jalan rusak</strong><span className="mini-location">Lokasi terdeteksi</span><b>Sukoharjo, Jawa Tengah</b><small>Menunggu penanganan <span>-&gt;</span></small></div></div></section>

      <CommunityStats />

      <section id="cara-kerja" className="process section-wrap"><div className="section-heading"><div><p className="eyebrow"><span /> Cara kerja JALANIN</p><h2>Semudah melihat,<br /><em>melaporkan, dan mengawal.</em></h2></div><p>Setiap laporan melewati proses yang jelas agar informasi jalan dapat dipercaya dan ditindaklanjuti.</p></div><div className="process-line">{[{ number: "01", title: "TEMUKAN", text: "Temukan jalan yang mengalami kerusakan." }, { number: "02", title: "LAPORKAN", text: "Kirim foto, lokasi, dan kondisi jalan." }, { number: "03", title: "PANTAU", text: "Ikuti perkembangan laporan sampai ditindaklanjuti." }].map((step) => <article key={step.number}><b>{step.number}</b><span className="process-icon">{step.number === "01" ? "⌖" : step.number === "02" ? "↗" : "◌"}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>

      <section id="tentang" className="features section-wrap"><div className="features-heading"><p className="eyebrow"><span /> Semua yang dibutuhkan</p><h2>Semua yang kamu<br /><em>butuhkan untuk melaporkan jalan.</em></h2><Link href="/reports/new" className="text-link">Mulai dari sekarang <span>-&gt;</span></Link></div><div className="feature-list"><article><span className="feature-icon">⌖</span><div><h3>Lokasi akurat</h3><p>Tandai titik kerusakan dengan lokasi yang mudah ditemukan.</p></div></article><article><span className="feature-icon">□</span><div><h3>Foto &amp; bukti</h3><p>Lengkapi laporan dengan kondisi nyata di lapangan.</p></div></article><article><span className="feature-icon">◷</span><div><h3>Status laporan</h3><p>Pantau setiap tahap, dari dikirim sampai ditangani.</p></div></article><article><span className="feature-icon">◎</span><div><h3>Peta kondisi</h3><p>Lihat masalah jalan yang sedang terjadi di sekitarmu.</p></div></article></div></section>

      <section className="map-explore section-wrap"><div className="map-explore-copy"><p className="eyebrow"><span /> Eksplorasi kondisi jalan</p><h2>Lihat kondisi jalan<br /><em>di sekitar kamu.</em></h2><p>Peta publik JALANIN menghubungkan laporan warga dengan lokasi nyata, sehingga kamu tahu apa yang perlu diperhatikan.</p><Link href="/map" className="button button-dark">Buka peta kondisi <span>-&gt;</span></Link></div><CommunityMapPreview /></section>

      <section className="story section-wrap"><div className="story-image"><div className="story-photo" /><span className="story-stamp">Untuk<br /><b>kota kita</b></span></div><div className="story-copy"><p className="eyebrow"><span /> Mengapa JALANIN</p><h2>Satu laporan kecil<br /><em>bisa membawa perubahan besar.</em></h2><p>Jalan yang aman bukan hanya soal aspal. Ia adalah akses menuju sekolah, pekerjaan, keluarga, dan kesempatan. Dengan berbagi informasi, kita membantu kota mengambil keputusan yang lebih baik.</p><Link href="/map" className="text-link">Kenapa JALANIN? <span>-&gt;</span></Link></div></section>

      <section id="laporan" className="latest section-wrap"><div className="section-heading"><div><p className="eyebrow"><span /> Dari komunitas</p><h2>Laporan terbaru di sekitar kita.</h2></div><Link href="/map" className="text-link">Buka semua laporan <span>-&gt;</span></Link></div><CommunityLatestReports /></section>

      <section className="final-cta section-wrap"><div><p className="eyebrow"><span /> Mulai dari sekitarmu</p><h2>Melihat jalan rusak?</h2><p>Jangan hanya melewatinya. Laporkan dan bantu wujudkan jalan yang lebih baik.</p></div><Link href="/reports/new" className="button button-light">Laporkan jalan rusak <span>-&gt;</span></Link></section>
    </main>

    <footer><div className="footer-inner section-wrap"><div className="footer-brand"><Link href="/" className="brand brand-light"><span className="brand-logo" aria-hidden="true" /><span>JALANIN</span></Link><p>Lapor jalan rusak,<br />wujudkan perubahan.</p></div><div className="footer-column"><b>Jelajahi</b><div className="footer-links"><Link href="/map">Peta kondisi</Link><a href="#cara-kerja">Cara kerja</a><a href="#laporan">Laporan terbaru</a></div></div><div className="footer-column"><b>Partisipasi</b><div className="footer-links"><Link href="/reports/new">Buat laporan</Link><Link href="/login">Masuk</Link><Link href="/register">Daftar</Link></div></div><div className="footer-column"><b>Bantuan</b><div className="footer-links"><a href="mailto:halo@jalanin.id">Kontak</a><a href="#tentang">Tentang JALANIN</a><a href="/docs/SECURITY.md">Kebijakan privasi</a></div></div></div><div className="footer-bottom section-wrap"><span>(c) 2026 JALANIN</span><span>Jalan Aman, Kota Nyaman.</span><span className="footer-status"><span /> Sistem publik aktif</span></div></footer>
  </div>;
}
